#!/bin/sh
#Installs Mathematica fonts on a Linux machine.
#by Drew Harris

#Defaults
XINIT_LOCATION=/etc/X11/xinit
MATH_FONT_LOCATION=/opt/mathfonts

if [ $(whoami) != 'root' ]
        then
                echo "Please run this command with sudo or as root."
                exit
fi

#Execute
mkdir $MATH_FONT_LOCATION
cd $MATH_FONT_LOCATION
wget http://support.wolfram.com/technotes/MathematicaV7FontsLinux.tar.gz
tar xfz MathematicaV7FontsLinux.tar.gz
xset fp+ $MATH_FONT_LOCATION/Fonts/Type1
xset fp+ $MATH_FONT_LOCATION/Fonts/BDF
xset fp rehash

#Store in xinitrc
bash -c "echo 'xset fp+ /opt/mathfonts/Fonts/Type1' >> $XINIT_LOCATION/xinitrc"
bash -c "echo 'xset fp+ /opt/mathfonts/Fonts/BDF' >> $XINIT_LOCATION/xinitrc"
bash -c "echo 'xset fp rehash' >> $XINIT_LOCATION/xinitrc"

#Clean up
cd $MATH_FONT_LOCATION
rm MathematicaV7FontsLinux.tar.gz

echo "Done."


